SmartHomeProject/Controllers/DeviceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SmartHomeProject.ConnectionManager;
using SmartHomeProject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace SmartHomeProject.Controllers
{
    public class DeviceController : Controller
    {
        private readonly ILogger<DeviceController> _logger;

        public DeviceController(ILogger<DeviceController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult JarvisControl()
        {
            var pageModel = new ControlModel { DeviceModels = DatabaseManager.getDeviceModels() };
            return View(pageModel);
        }


        [HttpGet]
        public IActionResult DeviceFunctions()
        {
            var pageModel = new DeviceFunctionsModel { DeviceModels = DatabaseManager.getDeviceModels() };
            return View(pageModel);
        }

        [HttpPost]
        public IActionResult addDeviceFunction(int deviceID, string functionname, int functionpin, bool RGB)
        {
            var result = false;
            try
            {
                result = DatabaseManager.AddFunctionToDevice(deviceID, functionname, (byte)functionpin, RGB);
            }
            catch (Exception e)
            {
                result = false;
                Logger.Logger.logError(Logger.Logger.Category.DEVICE_CONTROLLER, e.Message, e);
            }

            var pageModel = new DeviceFunctionsModel
            {
                DeviceModels = DatabaseManager.getDeviceModels(),
                addedFunction = true,
                addedSuccess = result,
                deviceSelected = true,
                functionNameAdded = functionname,
                selectedDeviceID = deviceID
            };
            return View("DeviceFunctions", pageModel);
        }

        [HttpGet]
        public IActionResult ControlFunction(int functionID, string deviceName)
        {
            var pageModel = new ControlModel { DeviceModels = DatabaseManager.getDeviceModels() };
            var modelsD = new DeviceManageModel { DeviceModels = DatabaseManager.getDeviceModels() };


            for (var i = 0; i < modelsD.DeviceModels.Length; i++)
            {
                if (modelsD.DeviceModels[i].name == deviceName)
                {
                    for (var k = 0; k < modelsD.DeviceModels[i].DeviceFunctions.Count; k++)
                    {
                        if (modelsD.DeviceModels[i].DeviceFunctions[k].functionID == functionID)
                        {
                            //Hier müsste dann an den server geschickt werden und der state geändert werden umgehe das erstmal
                            modelsD.DeviceModels[i].DeviceFunctions[k].executeFunction();
                        }
                    }
                }
            }

            return RedirectToAction("JarvisControl", pageModel);
            //return View("JarvisControl", pageModel);
        }

        [HttpPost]
        public IActionResult EditDeviceSettings(string selectedDevice, string deviceNameNew, string deviceType,
            string deviceDescription, string deviceIP, string devicePort, string deviceLocation)
        {
            var result = DatabaseManager.UpdateDevice(selectedDevice, deviceNameNew, deviceType, deviceDescription,
                deviceIP, devicePort, deviceLocation);
            var pageModel = new DeviceEditModel
            {
                selectedDevice = deviceNameNew,
                DeviceModels = DatabaseManager.getDeviceModels(),
                deviceNameEdited = selectedDevice,
                editingFailed = !result
            };
            return View("EditDevice", pageModel);
        }

        [HttpGet]
        public IActionResult DeviceManage()
        {
            var pageModel = new DeviceManageModel { DeviceModels = DatabaseManager.getDeviceModels() };
            return View(pageModel);
        }

        [HttpGet]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult EditDevice()
        {
            var pageModel = new DeviceEditModel { DeviceModels = DatabaseManager.getDeviceModels() };
            return View("EditDevice", pageModel);
        }

        [HttpPost]
        public IActionResult EditDevice(string model)
        {
            var pageModel = new DeviceEditModel
            { DeviceModels = DatabaseManager.getDeviceModels(), selectedDeviceName = model };
            return View("EditDevice", pageModel);
        }

        [HttpPost]
        public IActionResult AddNewSensor(int deviceIDSensor)
        {
            var rnd = new Random();
            const string python = "GPIO.setup(PIN[0], GPIO.IN)\r\nreturn GPIO.input(PIN[0])";
            var result = false;
            var sensorname = "New Sensor <" + rnd.Next(0, 9999) + ">";
            try
            {
                result = DatabaseManager.AddSensorToDevice(deviceIDSensor, sensorname, new byte[] { },
                    python);
            }
            catch (Exception e)
            {
                if (Logger.Logger.VERBOSE_LOG)
                {
                    Logger.Logger.logError(Logger.Logger.Category.DEVICE_FUNCTION, e.Message, e);
                }

                result = false;
            }

            var pageModel = new DeviceFunctionsModel
            {
                selectedDeviceID = deviceIDSensor,
                deviceSelected = true,
                DeviceModels = DatabaseManager.getDeviceModels(),
                sensorName = sensorname,
                sensorAdded = true,
                sensorAddSuccess = result
            };
            return View("DeviceFunctions", pageModel);
        }

        [HttpPost]
        public IActionResult EditSensor(int deviceIDSensor, int sensorOptions, string sensorname,
            string SensorGPIO_PINS,
            string SensorLocation, string content, string method)
        {
            try
            {
                Console.WriteLine("Werte: " + deviceIDSensor + " " + sensorOptions + " " + sensorname + " " +
                                  SensorGPIO_PINS + " " + SensorLocation + " " + content + " " + method);
                var result = false;
                if (method == "Delete")
                {
                    result = DatabaseManager.DeleteSensor(sensorOptions);
                }
                else
                {
                    var pins = new List<byte>();
                    if (!string.IsNullOrEmpty(SensorGPIO_PINS))
                    {
                        var split = SensorGPIO_PINS.Split(";");
                        for (var i = 0; i < split.Length; i++)
                        {
                            split[i] = split[i].Trim();
                            if (!string.IsNullOrEmpty(split[i]))
                            {
                                pins.Add(byte.Parse(split[i]));
                            }
                        }
                    }

                    result = DatabaseManager.UpdateSensor(sensorOptions, sensorname, pins.ToArray(), content,
                        SensorLocation);
                }

                if (result)
                {
                    var pageModel = new DeviceFunctionsModel
                    {
                        sensorEdited = true,
                        sensorEditetSuccess = result,
                        sensorName = sensorname,
                        deviceSelected = true,
                        selectedDeviceID = deviceIDSensor,
                        DeviceModels = DatabaseManager.getDeviceModels()
                    };
                    return View("DeviceFunctions", pageModel);
                }
                else
                {
                    var pageModel = new DeviceFunctionsModel
                    {
                        sensorEdited = true,
                        sensorEditetSuccess = result,
                        sensorName = DatabaseManager.getSensornameById(sensorOptions),
                        deviceSelected = true,
                        selectedDeviceID = deviceIDSensor,
                        DeviceModels = DatabaseManager.getDeviceModels()
                    };
                    return View("DeviceFunctions", pageModel);
                }
            }
            catch (Exception e)
            {
                if (Logger.Logger.VERBOSE_LOG)
                {
                    Logger.Logger.logError(Logger.Logger.Category.DEVICE_CONTROLLER, e.Message, e);
                }

                var pageModel = new DeviceFunctionsModel
                {
                    sensorEdited = true,
                    sensorEditetSuccess = false,
                    DeviceModels = DatabaseManager.getDeviceModels()
                };
                return View("DeviceFunctions", pageModel);
            }
        }

        [HttpPost]
        public ActionResult EditDeviceFunction(int deviceFunctions, string functionnameEdit, int pinEdit, string method,
            bool rgbEdit)
        {
            var editResult = false;
            var save = false;
            var delete = false;
            var deleteResult = false;
            if (method == "Save")
            {
                save = true;
                try
                {
                    editResult = DatabaseManager.UpdateDeviceFunction(deviceFunctions, functionnameEdit, (byte)pinEdit,
                        null, rgbEdit);
                }
                catch (Exception e)
                {
                    Logger.Logger.logError(Logger.Logger.Category.DEVICE_CONTROLLER, e.Message, e);
                    editResult = false;
                }
            }
            else if (method == "Delete")
            {
                delete = true;

SmartHomeProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartHomeProject</title>
    <!---<link rel="stylesheet" href="~/lib/bootstrap/dist/css/booststrap-Litera.css"/>-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/themes/@SmartHomeProject.ConnectionManager.DatabaseManager.getBootstrap()" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-colorpicker.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-colorpicker.css" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-robot"></i> Jarvis Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Device" asp-action="DeviceManage"><i class="fas fa-server"></i> Manage Devices<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Device" asp-action="AddDevice"><i class="fas fa-plus-square"></i> Add Device<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Device" asp-action="EditDevice"><i class="fas fa-edit"></i> Edit Device<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Device" asp-action="DeviceFunctions"><i class="fas fa-running"></i> Device Functions<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Device" asp-action="JarvisControl"><i class="fas fa-toolbox"></i> Jarvis Control<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Settings"><i class="fas fa-sliders-h"></i> Settings<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" style="width: 30%;">
                <input class="form-control mr-sm-2" type="text" id="search"placeholder="Search Google" style="width: 70%;">
                <button class="btn btn-secondary my-2 my-sm-0" style="width: 25%;"onclick="window.location.href = 'https://www.google.com/search?q=' + document.getElementById('search').value;return false;"><i class="fas fa-search"></i> Search</button>
            </form>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Jarvis Home -
        <a style="margin-left: 0.25em; margin-right: 0.25em;" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy🔐</a> -
        <!--<a style="margin-left: 0.25em; margin-right: 0.25em;" asp-area="" asp-controller="Home" asp-action="Donation">Support us with a donation❤</a>-->
        <!--<a style="margin-left: 0.25em; margin-right: 0.25em;" href="https://github.com/CodingTarik/SmartHomeProject">GitHub <i class="fab fa-github"></i></a>-->
        <a style="margin-left: 0.25em; margin-right: 0.25em;" asp-controller="home asp-action="Credits">Credits<i class="fas fa-user-friends"></i></a> -
        <a style="margin-left: 0.25em; margin-right: 0.25em;" asp-controller="home" asp-action="Disclaimer">Disclaimer</a><i class="fas fa-exclamation-triangle"></i> 
        <br />
        <div>Icons created by <a href="https://www.flaticon.com/de/autoren/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/de/" title="Flaticon">www.flaticon.com</a></div>
    </div>
</footer>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="/js/NavbarSelect.js"></script>
@RenderSection("Scripts", false)
</body>
</html>